### PR TITLE
Rename packet variables to be human-readable

### PR DESCRIPTION
**Pull request by juzsal**

### CODE REVIEW

**Comment by quixoft** [comment]
Yuch, I will be holding my nose applying that. It's going to slow the python parsing down, waste band width and memory. Will do it tomorrow, I need to learn how and it's a bit late to start

**Comment by juzsal** [comment]
You said yourself that there isn't any bandwidth problem on the Arduino. We're talking about a couple of extra bytes which will result in a negligible performance hit, with a huge benefit in readability.

**Comment by quixoft** [comment]
Sorry, where is the patch for the corresponding python client Ann's server we need to modify the key words in all three. If that gets applied it will break the system

**Comment by juzsal** [comment]
They will come in separate pull requests for their corresponding repositories in a while.

**Comment by quixoft** [comment]
Ok, I am still on my phone , tomorrow I will do it. The update to the python is not trivial , what is a are you using

**Comment by quixoft** [comment]
Sorry what IDE are you using

**Pull request merged**
